# This workflow will install Python dependencies, run tests and lint with a single version of Python, for the Orion CTP
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Orion Automated Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  discussions: write
  issues: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run the acquirer
      run: |
        python acquirer.py
    - name: run the trainer
      run: |
        python trainer.py
    - name: run the publisher
      run: |
        python publisher.py
